import type { CycleSpec, PhaseSpec } from "../../synapse/types.js";

function truncate(value: string, max = 400): string {
  if (!value) {
    return "";
  }
  return value.length <= max ? value : `${value.slice(0, max)}...`;
}

function asRecord(value: unknown): Record<string, unknown> | null {
  return value && typeof value === "object" && !Array.isArray(value)
    ? value as Record<string, unknown>
    : null;
}

function asString(value: unknown): string | null {
  return typeof value === "string" && value.trim() ? value.trim() : null;
}

function asStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return [];
  }
  return value
    .filter((item): item is string => typeof item === "string")
    .map((item) => item.trim())
    .filter(Boolean);
}

function uniq(items: string[]): string[] {
  return Array.from(new Set(items));
}

interface CompletedPhaseContext {
  id: string;
  type: string;
  completed_at: string | null;
  summary?: string;
  files_modified?: string[];
  changed_files?: string[];
  frontend_tweak_required?: boolean;
}

function phaseIndex(cycle: CycleSpec, phase: PhaseSpec): number {
  return cycle.phases.findIndex((p) => p.id === phase.id);
}

function extractCompletedPhaseContext(phase: PhaseSpec): CompletedPhaseContext {
  const output = asRecord(phase.output);
  const report = asRecord(output?.report);
  const summary = asString(report?.summary) || asString(report?.message);
  const filesModified = asStringArray(report?.files_modified).slice(0, 20);
  const changedFiles = asStringArray(output?.changed_files).slice(0, 20);
  const frontendTweakRequired = typeof output?.frontend_tweak_required === "boolean"
    ? output.frontend_tweak_required
    : undefined;

  return {
    id: phase.id,
    type: phase.type,
    completed_at: phase.finished_at,
    ...(summary ? { summary: truncate(summary, 300) } : {}),
    ...(filesModified.length ? { files_modified: filesModified } : {}),
    ...(changedFiles.length ? { changed_files: changedFiles } : {}),
    ...(typeof frontendTweakRequired === "boolean" ? { frontend_tweak_required: frontendTweakRequired } : {})
  };
}

function recentCompletedPhases(cycle: CycleSpec, phase: PhaseSpec): CompletedPhaseContext[] {
  const idx = phaseIndex(cycle, phase);
  const candidates = cycle.phases
    .filter((p, i) => p.status === "DONE" && (idx < 0 || i < idx))
    .map(extractCompletedPhaseContext);

  return candidates.slice(-3);
}

function suggestedStartFiles(recent: CompletedPhaseContext[]): string[] {
  const latest = recent[recent.length - 1];
  if (!latest) {
    return [];
  }

  const fromLatest = [
    ...(latest.files_modified || []),
    ...(latest.changed_files || [])
  ];

  return uniq(fromLatest).slice(0, 12);
}

function retryContext(cycle: CycleSpec, phase: PhaseSpec): Record<string, unknown> | undefined {
  if (phase.attempt_count <= 1 || !cycle.last_error) {
    return undefined;
  }

  return {
    attempt: phase.attempt_count,
    max_attempts: phase.max_attempts,
    last_error: {
      code: cycle.last_error.code,
      message: truncate(cycle.last_error.message || "", 240)
    }
  };
}

export function buildWorkerPhaseContextBlock(cycle: CycleSpec, phase: PhaseSpec): string {
  const recentCompleted = recentCompletedPhases(cycle, phase);
  const retry = retryContext(cycle, phase);
  const startingFiles = suggestedStartFiles(recentCompleted);
  const context = {
    cycle_id: cycle.id,
    current_phase: {
      id: phase.id,
      type: phase.type,
      attempt: phase.attempt_count,
      max_attempts: phase.max_attempts
    },
    retry_context: retry || null,
    recent_completed_phases: recentCompleted,
    suggested_start_files: startingFiles
  };

  return [
    "Worker context (generated by Synapse, use this to reduce repo scanning):",
    "SYNAPSE_PHASE_CONTEXT_BEGIN",
    JSON.stringify(context, null, 2),
    "SYNAPSE_PHASE_CONTEXT_END"
  ].join("\n");
}

