import type { CycleSpec, PhaseSpec } from "../../../synapse/types.js";
import { readOrBuildRepoIndex, suggestFilesFromRepoIndex } from "../repoIndex.js";
import { readWorkerMemory } from "../workerMemory.js";
import { collectCandidateFileSeeds } from "./candidateSeeds.js";
import { recentCompletedPhases, suggestedStartFilesFromRecent } from "./completedPhase.js";
import { buildRetryContext } from "./retryContext.js";
import { readSeedFileSnippets } from "./snippets.js";
import { summarizeWorkerMemory } from "./workerMemoryView.js";

export async function buildWorkerPhaseContextBlock(
  cycle: CycleSpec,
  phase: PhaseSpec,
  opts: { storageDir?: string } = {}
): Promise<string> {
  const recentCompleted = recentCompletedPhases(cycle, phase);
  const retry = buildRetryContext(cycle, phase);
  const storageDir = opts.storageDir || ".synapse";
  const workerMemory = await readWorkerMemory(cycle.repo_root, storageDir, cycle.id).catch(() => null);
  const queryParts = [
    cycle.request_text,
    ...(cycle.constraints || []),
    ...recentCompleted.map((p) => p.summary || "").filter(Boolean),
    typeof retry?.last_error === "object" && retry?.last_error && typeof (retry.last_error as any).message === "string"
      ? (retry.last_error as any).message
      : ""
  ].filter(Boolean);
  const preseedPaths = [
    ...suggestedStartFilesFromRecent(recentCompleted),
    ...(workerMemory?.file_hints || []).map((h) => h.path)
  ];
  const repoIndexSuggestions = await readOrBuildRepoIndex(cycle.repo_root, storageDir).then((index) =>
    suggestFilesFromRepoIndex(index, queryParts.join("\n"), {
      limit: 8,
      exclude: preseedPaths
    }).map((s) => ({ path: s.path, score: s.score, matched_tokens: s.matched_tokens }))
  ).catch(() => []);
  const candidateSeeds = collectCandidateFileSeeds(cycle, phase, recentCompleted, retry, workerMemory, repoIndexSuggestions);
  const fileSnippets = await readSeedFileSnippets(cycle.repo_root, candidateSeeds);

  const context = {
    cycle_id: cycle.id,
    current_phase: {
      id: phase.id,
      type: phase.type,
      attempt: phase.attempt_count,
      max_attempts: phase.max_attempts
    },
    retry_context: retry || null,
    recent_completed_phases: recentCompleted,
    suggested_start_files: candidateSeeds.map((seed) => seed.path),
    repo_index_suggestions: repoIndexSuggestions,
    seed_file_snippets: fileSnippets,
    worker_memory: summarizeWorkerMemory(workerMemory)
  };

  return [
    "Worker context (generated by Synapse, use this to reduce repo scanning):",
    "SYNAPSE_PHASE_CONTEXT_BEGIN",
    JSON.stringify(context, null, 2),
    "SYNAPSE_PHASE_CONTEXT_END"
  ].join("\n");
}
